name: Deploy to Ubuntu Server

on:
  workflow_dispatch:   # Chạy thủ công
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull latest image from Docker Hub
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/department-service
          docker pull $IMAGE_NAME:latest
